name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          sbom: true
          provenance: mode=max
          outputs: type=registry
          platforms: |
            linux/amd64
            linux/arm64
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/linux-hostapd-hs20-dhcpd:latest, ghcr.io/${{ secrets.DOCKER_USERNAME }}/linux-hostapd-hs20-dhcpd:latest
          github-token: ${{ secrets.PAT_TOKEN }}